// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycrsnhfrmwoptnshbyqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcnNuaGZybXdvcHRuc2hieXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDk3MzAsImV4cCI6MjA2NTUyNTczMH0.sAuwHwNpXeyGgPEuTJCHZrWuFV-HEPMql5lpngKyZOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);